/**
 * Notification domain logic — the single implementation both surfaces call.
 *
 * Replaces:
 *   lib/storage/notifications.js          (reader, keyed on `read`)
 *   lib/mastodon/routes/notifications.js  (Mastodon lane, keyed on `dismissed`)
 *
 * DD-3 — those two fields never observed each other, so dismissing on the phone
 * left the item unread on the desktop and vice versa. Both now read and write
 * one nullable `readAt` timestamp. Marking read anywhere marks it read
 * everywhere, which is the defect (AP-D2) this module exists to close.
 *
 * `read` and `dismissed` are still written alongside `readAt` for one release
 * (M-1a). That is deliberate: it keeps a rollback to the previous registry pin
 * a pure code revert. M-1b removes the dual-write.
 *
 * @module core/notifications
 */
import { buildPage, decodeCursor, encodeCursor } from "./cursor.js";
import { clampLimit } from "./timeline.js";

/**
 * Build the base filter for a notification query.
 *
 * @param {object} [options]
 * @param {boolean} [options.unreadOnly]
 * @param {string[]} [options.types] - Internal types ("like","boost","follow",…)
 * @param {string[]} [options.excludeTypes]
 * @returns {object}
 */
export function buildNotificationFilter(options = {}) {
  const filter = {};

  if (options.unreadOnly) {
    filter.readAt = null;
  }

  if (options.types?.length) {
    filter.type = { $in: options.types };
  } else if (options.excludeTypes?.length) {
    filter.type = { $nin: options.excludeTypes };
  }

  return filter;
}

/**
 * Fetch a page of notifications, newest first.
 *
 * @param {object} collections
 * @param {object} [options] - buildNotificationFilter options, plus limit/cursors
 * @returns {Promise<{items: object[], before: string|null, after: string|null}>}
 */
export async function getNotifications(collections, options = {}) {
  const limit = clampLimit(options.limit);
  const base = buildNotificationFilter(options);

  const { filter, sort, reverse } = buildPage(base, options);

  // Notifications sort on `published` (when the event happened) rather than
  // `receivedAt`. Unlike timeline posts there is no late-arrival problem: a
  // notification is generated by an activity we just processed, so the two are
  // effectively the same instant.
  const sortSpec = reverse ? { published: 1, _id: 1 } : { published: -1, _id: -1 };

  const raw = await collections.ap_notifications
    .find(filter)
    .sort(sortSpec)
    .limit(limit)
    .toArray();

  const items = reverse ? raw.reverse() : raw;

  return {
    items,
    before: items.length === limit ? encodeCursor(items.at(-1)) : null,
    after: items.length > 0 ? encodeCursor(items[0]) : null,
  };
}

/**
 * Fetch one notification by the opaque id an adapter received from a client.
 *
 * Takes a STRING, not an ObjectId: parsing is core's job, so no adapter needs
 * to import mongodb (DD-2, boundary rule 5.2). Returns null for a malformed id
 * rather than throwing — that is a 404, not a 500.
 *
 * @param {object} collections
 * @param {string} id
 * @returns {Promise<object|null>}
 */
export async function getNotification(collections, id) {
  const objectId = decodeCursor(id);
  if (!objectId) return null;
  return collections.ap_notifications.findOne({ _id: objectId });
}

/**
 * Mark notifications read. Idempotent.
 *
 * `ids` are opaque STRINGS as received from a client; core decodes them.
 *
 * @param {object} collections
 * @param {object} selector - { uids?: string[], ids?: string[] } — omit both for ALL
 * @returns {Promise<number>} documents newly marked
 */
export async function markRead(collections, selector = {}) {
  const filter = { readAt: null };

  if (selector.uids?.length) {
    filter.uid = { $in: selector.uids };
  } else if (selector.ids?.length) {
    const objectIds = selector.ids.map(decodeCursor).filter(Boolean);
    if (objectIds.length === 0) return 0;
    filter._id = { $in: objectIds };
  }

  const now = new Date().toISOString();

  const { modifiedCount } = await collections.ap_notifications.updateMany(filter, {
    // `read` and `dismissed` are the M-1a dual-write. Both legacy fields are set
    // so either lane's un-migrated code path still behaves correctly during the
    // rollback window.
    $set: { readAt: now, read: true, dismissed: true },
  });

  return modifiedCount;
}

/**
 * Count unread notifications.
 *
 * @param {object} collections
 * @param {object} [options] - buildNotificationFilter options
 * @returns {Promise<number>}
 */
export async function countUnread(collections, options = {}) {
  return collections.ap_notifications.countDocuments(
    buildNotificationFilter({ ...options, unreadOnly: true }),
  );
}

/**
 * Unread counts grouped by type — powers the reader's per-tab badges.
 *
 * @param {object} collections
 * @param {boolean} [unreadOnly=false]
 * @returns {Promise<Record<string, number>>}
 */
export async function countByType(collections, unreadOnly = false) {
  const match = unreadOnly ? { readAt: null } : {};

  const rows = await collections.ap_notifications
    .aggregate([{ $match: match }, { $group: { _id: "$type", n: { $sum: 1 } } }])
    .toArray();

  return Object.fromEntries(rows.map((r) => [r._id, r.n]));
}

/**
 * Hard-delete a notification.
 *
 * Distinct from marking read: the reader offers an explicit delete, and DD-3
 * keeps that separate so a client tapping "clear" cannot destroy history.
 *
 * @param {object} collections
 * @param {string} uid
 * @returns {Promise<number>}
 */
export async function deleteNotification(collections, uid) {
  const { deletedCount } = await collections.ap_notifications.deleteOne({ uid });
  return deletedCount;
}
